######################################################################
# Automatically generated by qmake (3.0) V nov. 8 16:54:06 2015
######################################################################

TEMPLATE = app
TARGET = sortviz

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += mainview.hpp sortable.hpp sortthread.hpp \
    rectfiller.hpp
SOURCES += main.cpp mainview.cpp sortable.cpp

CONFIG += c++11
